import pandas as pd
from faker import Faker

#Setting up the Faker()
fake_data = Faker()

print ("Security Layer Activated: Initializing PII Anonymization Engine...")

#Raw data or import from another .CSV file - df = pd.read_csv('abc.csv'). 

#Previous raw code snippet for reference
#raw_data = {
#    'User_Name': ['Alice Wang', 'Bob Dennis', 'Jenny Batina'],
#    'Password': ['Pa$$word123', 'Secr3tP@ss', 'testP@ss123'],
#    'Email_ID': ['aliwan@yahoo.com', 'bobden@hotmail.com', 'jenbat@gmail.com']
#}
#Putting it in DataFrame
#df = pd.DataFrame(raw_data)

#Importing from raw_data.csv file generated by raw-data_generator.py here using try block to catch any errors.
try: 
    df = pd.read_csv('raw_data.csv') 
    print("Raw data imported successfully from 'raw_data.csv'.")
except FileNotFoundError:
    print("Error: 'raw_data.csv' file not found. Please ensure the file exists in pwd (or) Run raw_data_generator.py to generate the file first.")
    exit()

num_rows = len(df)
print(f"Successfully loaded {num_rows} records. Commencing data masking...")

#Data Transformation
df['User_Name'] = [fake_data.name() for name in range(num_rows)]
df['Password'] = [fake_data.password() for password in range(num_rows)]
df['Email_ID'] = [fake_data.email() for email in range(num_rows)]
df['Phone'] = [fake_data.phone_number() for phone in range(num_rows)]
df['Address'] = [fake_data.address() for address in range(num_rows)]
df['IP_Address'] = [fake_data.ipv4_private() for ip in range(num_rows)]

print("\n--- Data Masked Successfully ---")
print(df.head())  # Prints first 5 rows r print(df) --> print all rows
print("\nData is now safe to use in Test environments, maintaining privacy :)")

#Exporting
df.to_csv('masked_pii_data.csv', index=False) #removing index nums
print("\nSecure dataset exported successfully to 'masked_pii_data.csv'.")